# -*- coding: utf-8 -*-
"""prefixSum_ queries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Answer multiple range sum queries efficiently
Time Complexity : O(N + Q)
Space Complexity: O(N)

"""
def prefixSumArray(array):
  prefix = [0] * len(array)
  prefix[0] = array[0]
  for number in range(1,len(array)):
    prefix[number] = prefix[number-1] + array[number]
  return prefix
def prefixSumQuer(array,quer):
  results = []
  for L,R in quer:
    if L== 0 :
      results.append(array[R])
    else:
       results.append(array[R] - array[L-1])
  return results
if __name__=="__main__":
  arr = list(map(int,input().split()))
  result = prefixSumArray(arr)
  print(result)
  queries=[(0,2),(1,4),(3,5)]
  print("Queries:",prefixSumQuer(result,queries))