# -*- coding: utf-8 -*-
"""prefixSum_LR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Find the sum of elements between index L and R using prefix sum
Time Complexity : O(N)
Space Complexity: O(N)

"""
def prefixSumArray(array):
  prefix = [0] * len(array)
  prefix[0] = array[0]
  for number in range(1,len(array)):
    prefix[number] = prefix[number-1] + array[number]
  return prefix
def prefixSumLR(array,L,R):
  if L == 0 :
    return array[R]
  else:
    return array[R]-array[L-1]
if __name__=="__main__":
  arr = list(map(int,input().split()))
  result = prefixSumArray(arr)
  print(result)
  L = int(input())
  R = int(input())
  print(prefixSumLR(result,L,R))