# -*- coding: utf-8 -*-
"""prefix _sum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Build a prefix sum array from a given array
Time Complexity : O(N)
Space Complexity: O(N)

"""
def prefixSumArray(array):
  prefix = [0] * len(array)
  prefix[0] = array[0]
  for number in range(1,len(array)):
    prefix[number] = prefix[number-1] + array[number]
  return prefix
if __name__=="__main__":
  arr = list(map(int,input().split()))
  print(prefixSumArray(arr))