# -*- coding: utf-8 -*-
"""Check_array_Sorted

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Check if array is Sorted or Not Sorted
Time Complexity : O(N log N)
Space Complexity: O(N)
"""
def sortedOrNotSorted(arr):
  sortArray = sorted(arr)
  if arr == sortArray:
    print('Sorted')
  else:
    print('Not Sorted')
"""
Time Complexity : O(N)
Space Complexity: O(1)
"""
def sortedOrNotSorted2(arr):
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            print("Not Sorted")
            return
    print("Sorted")

if __name__ == "__main__":
    arrayList = list(map(int, input().split()))
    sortedOrNotSorted(arrayList)
    sortedOrNotSorted2(arrayList)