# -*- coding: utf-8 -*-
"""Display_Even_Odd_index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Display Even And Odd Index
Time Complexity : O(N)
Space Complexity: O(1)
"""
def evenOddIndex(arr):
  for i in range(len(arr)):
    if i % 2 == 0:
      print('Even Index:',arr[i])
    else:
      print('Odd Index:',arr[i])
if __name__ == "__main__":
    arrayList = list(map(int, input().split()))
    evenOddIndex(arrayList)