# -*- coding: utf-8 -*-
"""duplicates(sorted)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Remove duplicates (sorted array)
Time Complexity : O(N)
Space Complexity: O(1)

"""
def remove_duplicates(arr):
    if not arr:
        return 0
    i = 0
    for j in range(1, len(arr)):
        if arr[j] != arr[i]:
            i += 1
            arr[i] = arr[j]
    return i + 1
if __name__ == "__main__":
  arr = list(map(int,input().split()))
  length = remove_duplicates(arr)
  print(arr[:length])