# -*- coding: utf-8 -*-
"""frequency_elements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Count frequency of elements
Time Complexity : O(N)
Space Complexity: O(N)

"""
def frequencyCount(array):
  freq = {}
  for num in arr:
    freq[num] = freq.get(num,0) + 1
  for key, value in freq.items():
    print(key, "-->>", value)
if __name__ == "__main__":
  arr = list(map(int,input().split()))
  frequencyCount(arr)