# -*- coding: utf-8 -*-
"""largest_smallest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Find The Largest And Smallest Elements or Number
Time Complexity: O(n)
Space Complexity: O(1)

"""
def findLargestAndSmallest(numbers):
    largest = smallest = numbers[0]

    for i in numbers:
        if i > largest:
            largest = i
        if i < smallest:
            smallest = i

    return largest, smallest
number = int(input())
array = []
for _ in range(number):
    array.append(int(input()))
print(findLargestAndSmallest(array))