# -*- coding: utf-8 -*-
"""largest_smallest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Find the largest and smallest element in an array

Approach:
- Initialize both smallest and largest with the first element
- Traverse the array once and update values

Time Complexity: O(N)pace Complexity: O(1)
"""

def find_largest_smallest(arr):
    smallest = arr[0]
    largest = arr[0]

    for num in arr:
        if num < smallest:
            smallest = num
        if num > largest:
            largest = num

    return smallest, largest
if __name__ == "__main__":
    arr = [1, 5, 6, 32, 8, 5]
    small, large = find_largest_smallest(arr)
    print("Smallest:", small)
    print("Largest:", large)