# -*- coding: utf-8 -*-
"""reverse_array

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Reverse The Given Array
Time Complexity : O(N)
Space Complexity: O(1)
"""
def reverseMethod1(arr):
  start = 0
  end = len(arr)-1
  while start < end :
    arr[start],arr[end] = arr[end],arr[start]
    start+=1
    end-=1
  print(arr)
elements = int(input())
array = []
for _ in range(elements):
  number = int(input())
  array.append(number)
reverseMethod1(array)