# -*- coding: utf-8 -*-
"""Rotate_K Steps

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Rotate Array By K Steps
Time Complexity : O(N)
Space Complexity: O(1)

"""
def rotate_array(arr, k):
    size = len(arr)
    k = k % size
    return arr[-k:] + arr[:-k]
if __name__=="__main__":
  array = list(map(int,input().split()))
  k = int(input())
  print(rotate_array(array, k))