# -*- coding: utf-8 -*-
"""Second _Largest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Find Second Largest Element In An Array
Time Complexity : O(N)
Space Complexity: O(1)

"""
def second_largest(arr):
    if len(arr) < 2:
        return None

    first = second = float('-inf')

    for num in arr:
        if num > first:
            second = first
            first = num
        elif first > num > second:
            second = num

    return second if second != float('-inf') else None

if __name__ == "__main__":
  arr = list(map(int,input().split()))
  print(second_largest(arr))
