# -*- coding: utf-8 -*-
"""zeros_to_end

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLBw_Jf2_1KjmgzM-zZOUvcibWupSIUp
"""

"""
Problem: Move all zeros to end
Time Complexity : O(N)
Space Complexity: O(N)

"""
def moveZeroes(arr):
    non_zero = []
    zero = []
    for num in arr:
        if num == 0:
            zero.append(num)
        else:
            non_zero.append(num)
    result = non_zero + zero
    print(result)
if __name__ == "__main__":
  array = list(map(int,input().split()))
  moveZeroes(array)